name: Build

on:
  push:
  pull_request:

# Restrict the GITHUB_TOKEN
permissions: {}

env:
  OCAML_DEFAULT_VERSION: 4.14.2
  # Add OPAMYES=true to the environment, this is usefill to replace `-y` option
  # in any opam call
  OPAMYES: true
  # Alt-Ergo's depext crashs with with-test flag to yes
  #   # The with-test flag is set to true to force installation of deps and
  #   # depext needed to run the alt-ergo tests
  #   OPAMWITHTEST: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-13
          - macos-14
          - ubuntu-latest
          - windows-latest
        ocaml-compiler:
          - 4.14.2

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true

      - name: Install dependencies
        run: opam exec -- make deps

      - name: Build alt-ergo with opam
        run: |
          opam exec -- make packages
          opam exec -- dune install -p alt-ergo --prefix=staging

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: altergo-${{matrix.os}}
          path: staging
